const GOT_POPULAR = 'GOT_POPULAR';
const GETTING_POPULAR = 'GETTING_POPULAR';
const GETTING_SEARCH = 'GETTING_SEARCH';
const GOT_SEARCH = 'GOT_SEARCH';
const GOT_GENRES = 'GOT_GENRES';
const GETTING_GENRES = 'GETTING_GENRES';
const TOGGLE_FILM_FAVORITES = 'TOGGLE_FILM_FAVORITES';
const GOT_FILM_CARD = 'GOT_FILM_CARD';
const GETTING_FILM_CARD = 'GETTING_FILM_CARD';

export {
    GOT_POPULAR,
    GETTING_POPULAR,
    GETTING_SEARCH,
    GOT_SEARCH,
    GOT_GENRES,
    GETTING_GENRES,
    TOGGLE_FILM_FAVORITES,
    GOT_FILM_CARD,
    GETTING_FILM_CARD
};
